alg:
  value: !!str ringsfl
num_worker:
  value: !!int 5
prop_lens:
  value: !!str 80:1:1:1:1
block_num:
  value: !!int 5
batch_size:
  value: !!int 64
dataset_name:
  value: !!str mnist
dataset_type:
  value: !!str iid
model_type:
  value: !!str mobilenet
lr:
  value: !!float 0.001
global_round:
  value: !!int 50
local_epoch:
  value: !!int 2
run_count:
  value: !!int 1
