
alg:
  value: !!str ringsfl_v2
num_worker:
  value: !!int 5
prop_lens:
  value: !!str 10:1:1:1:1
block_num:
  value: !!int 5
batch_size:
  value: !!int 64
dataset_name:
  value: !!str mnist
dataset_type:
  value: !!str iid
model_type:
  value: !!str cnn
cut_point:
  value: !!int 2
lr:
  value: !!float 0.06
global_round:
  value: !!int 50
local_epoch:
  value: !!int 2
