program: main.py
project: StalRingSFL 
entity: sjinglong
method: bayes
metric:
  name: acc
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
name: find-lr-lenet-noniid
parameters:
  lr: # 0.04
    max: 0.1
    min: 0.01
    distribution: uniform
  model_type:
    values: ["lenet"]
  num_worker:
    values: [5]
  prop_lens:
    values: ["8:1:1:1:1"]
  block_num:
    values: [5]
  batch_size:
    values: [64]
  dataset_name:
    values: ["mnist"]
  dataset_type:
    values: ["noniid"]
  global_round:
    values: [50]
  local_epoch:
    values: [2]
  alg:
    values: ["ringsfl_v2"]
  cut_point:
    values: [2]